/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transacciones_1_0;
import Clases.VariableGlobal;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import rojeru_san.RSPanelsSlider;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Formulario extends javax.swing.JFrame {

    private VariableGlobal conexion;
    private String[] titulos = {"id","Nombre","Nit","Direccion","Saldo"};
    public Formulario() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Transacciones");
        conexion = new VariableGlobal();
        botonRollBack.setEnabled(false);
        botonCommit.setEnabled(false);
        DialogNuevo.setTitle("Nuevo cliente");
        DialogNuevo.setLocationRelativeTo(null);
        DialogNuevo.setSize(404,430);
        //DialogNuevo.setDefaultCloseOperation(DialogNuevo.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuEmergente = new javax.swing.JPopupMenu();
        EmergenteEliminar = new javax.swing.JMenuItem();
        DialogNuevo = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        botonAceptar = new rojeru_san.RSButton();
        botonCancelar = new rojeru_san.RSButton();
        txtNombre = new rojeru_san.RSMTextFull();
        txtNit = new rojeru_san.RSMTextFull();
        txtDireccion = new rojeru_san.RSMTextFull();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonRecargarBD = new rojeru_san.RSButtonRiple();
        botonIniciarTran = new rojeru_san.RSButtonRiple();
        botonRollBack = new rojeru_san.RSButtonRiple();
        botonNuevaVentana = new rojeru_san.RSButton();
        botonCommit = new rojeru_san.RSButtonRiple();
        rsPanel = new rojeru_san.RSPanelsSlider();
        panelTabla = new javax.swing.JPanel();
        txtBuscar = new rojeru_san.RSMTextFull();
        botonBuscar = new rojeru_san.RSButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCliente = new rojerusan.RSTableMetro();
        comboClientes = new javax.swing.JComboBox<>();
        botonNuevo = new rojeru_san.RSButton();
        BarraDeMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ModificarAislamiento = new javax.swing.JMenu();
        ReadUncommitted = new javax.swing.JMenuItem();
        ReadCommitted = new javax.swing.JMenuItem();
        RepeatableRead = new javax.swing.JMenuItem();
        Serializable = new javax.swing.JMenuItem();
        VerAsilamiento = new javax.swing.JMenuItem();

        EmergenteEliminar.setText("Eliminar");
        EmergenteEliminar.setActionCommand("Eliminar");
        EmergenteEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergenteEliminarActionPerformed(evt);
            }
        });
        MenuEmergente.add(EmergenteEliminar);
        EmergenteEliminar.getAccessibleContext().setAccessibleName("Eliminar");

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/seo-social-web-network-internet_273_icon-icons.com_61489.png"))); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancel-cross_icon-icons.com_71726.png"))); // NOI18N
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        txtNombre.setPlaceholder("Nombre");

        txtNit.setPlaceholder("Nit");

        txtDireccion.setPlaceholder("Direccion");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout DialogNuevoLayout = new javax.swing.GroupLayout(DialogNuevo.getContentPane());
        DialogNuevo.getContentPane().setLayout(DialogNuevoLayout);
        DialogNuevoLayout.setHorizontalGroup(
            DialogNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DialogNuevoLayout.setVerticalGroup(
            DialogNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 112, 192)));

        botonRecargarBD.setText("Recargar BD");
        botonRecargarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecargarBDActionPerformed(evt);
            }
        });

        botonIniciarTran.setText("Iniciar Transaccion");
        botonIniciarTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarTranActionPerformed(evt);
            }
        });

        botonRollBack.setText("Retornar");
        botonRollBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRollBackActionPerformed(evt);
            }
        });

        botonNuevaVentana.setText("Nueva Ventana");
        botonNuevaVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaVentanaActionPerformed(evt);
            }
        });

        botonCommit.setText("Confirmar");
        botonCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCommitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonRollBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonRecargarBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonIniciarTran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonNuevaVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonCommit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonRecargarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(botonIniciarTran, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRollBack, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(botonNuevaVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        panelTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 112, 192)));

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/seo-social-web-network-internet_340_icon-icons.com_61497.png"))); // NOI18N
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaCliente.setComponentPopupMenu(MenuEmergente);
        jScrollPane1.setViewportView(TablaCliente);

        comboClientes.setBackground(new java.awt.Color(0, 112, 192));
        comboClientes.setEditable(true);
        comboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Deudores", "Sin deuda", " " }));

        botonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add-new-document_icon-icons.com_54068.png"))); // NOI18N
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(panelTablaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTablaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(botonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rsPanel.add(panelTabla, "card2");

        BarraDeMenu.setBackground(new java.awt.Color(0, 112, 192));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Aislamiento");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        ModificarAislamiento.setText("Modificar aislamiento");

        ReadUncommitted.setText("Leer no comprometido");
        ReadUncommitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadUncommittedActionPerformed(evt);
            }
        });
        ModificarAislamiento.add(ReadUncommitted);

        ReadCommitted.setText("Leer comprometido");
        ReadCommitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadCommittedActionPerformed(evt);
            }
        });
        ModificarAislamiento.add(ReadCommitted);

        RepeatableRead.setText("Leer repetido");
        RepeatableRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatableReadActionPerformed(evt);
            }
        });
        ModificarAislamiento.add(RepeatableRead);

        Serializable.setText("Serializable");
        Serializable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerializableActionPerformed(evt);
            }
        });
        ModificarAislamiento.add(Serializable);

        jMenu1.add(ModificarAislamiento);

        VerAsilamiento.setText("Ver aislamiento");
        VerAsilamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerAsilamientoActionPerformed(evt);
            }
        });
        jMenu1.add(VerAsilamiento);

        BarraDeMenu.add(jMenu1);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   //Cambia el nivel de aislamiento
    private void cambioAislamiento(String aisla){
        int resp = JOptionPane.showConfirmDialog(null,"¿Esta seguro de cambiar "+"\nel nivel de aislamiento a "+aisla+"?","¡Alerta"
        ,JOptionPane.YES_NO_OPTION);
        if(resp == 0){
           conexion.conexion.EjecutarInstruccion("SET GLOBAL TRANSACTION ISOLATION LEVEL "+aisla);//Ejecutamos la sentencia para cambiar el aislamiento
           JOptionPane.showMessageDialog(null,"El aislamiento fue cambiado");
           conexion.conexion.CerrarConexion();//Cerramos la conexion 
           conexion = new VariableGlobal();//Instanciamos un nuevamente la variable conexion. Para poder ver los cambios
        }
    }
    //Cargar tabla
    private void CargarTabla(String parametro,int itemCombo){
         String consulta = "select * from cliente";
        switch(itemCombo){
            case 0:
                
                if(parametro.length()>0){
                   consulta = consulta+" where id = "+parametro;
                }
                break;
            case 1:
                consulta = consulta + " where Saldo > 0";
                if(parametro.length()>0){
                    consulta = consulta + " and id = "+parametro;
                }
                break;
            case 2:
                consulta = consulta + " where Saldo = 0";
                if(parametro.length()>0){
                    consulta = consulta + " and id = "+parametro;
                }  
                break;
        }
        conexion.conexion.llenarTabla(titulos, TablaCliente, consulta);
    }
    
    //Ver el aislamiento de la base
    private void VerAsilamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerAsilamientoActionPerformed
        String nivelAislamiento = "";
        conexion.conexion.EjecutarConsulta("show variables like 'tx_isolation'");//Realizamos la consulta 
        ResultSet rs = conexion.conexion.getResultSet();//Obtenemos el ResultSet, que tiene los registros de la consulta
        try {
            while(rs.next()){//Recorremos todos los registros de la consulta. 
                nivelAislamiento = rs.getString("Value");//Retornamos el dato que este en la columna Values. Que es donde esta el nivel de aislamiento
            }
        } catch (Exception e) {
        }
        JOptionPane.showMessageDialog(null,"EL nivle de aislamiento es: "+nivelAislamiento,"",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_VerAsilamientoActionPerformed

    private void SerializableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerializableActionPerformed
        cambioAislamiento("SERIALIZABLE");
    }//GEN-LAST:event_SerializableActionPerformed

    private void RepeatableReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatableReadActionPerformed
        cambioAislamiento("REPEATABLE READ");
    }//GEN-LAST:event_RepeatableReadActionPerformed

    private void ReadCommittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadCommittedActionPerformed
        cambioAislamiento("READ COMMITTED");
    }//GEN-LAST:event_ReadCommittedActionPerformed

    private void ReadUncommittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadUncommittedActionPerformed
        cambioAislamiento("READ UNCOMMITTED");
    }//GEN-LAST:event_ReadUncommittedActionPerformed

    private void botonIniciarTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarTranActionPerformed
        conexion.conexion.EjecutarInstruccion("start transaction");
        botonIniciarTran.setEnabled(false);
        botonRollBack.setEnabled(true);
        botonCommit.setEnabled(true);
    }//GEN-LAST:event_botonIniciarTranActionPerformed

    private void botonRecargarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecargarBDActionPerformed
        conexion = new VariableGlobal();
    }//GEN-LAST:event_botonRecargarBDActionPerformed

    private void botonRollBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRollBackActionPerformed
        conexion.conexion.EjecutarInstruccion("rollback");
        botonRollBack.setEnabled(false);
        botonCommit.setEnabled(false);
        botonIniciarTran.setEnabled(true);
        CargarTabla("",comboClientes.getSelectedIndex());
    }//GEN-LAST:event_botonRollBackActionPerformed

    private void botonNuevaVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaVentanaActionPerformed
        //Transacciones_1_0.main(null);
        Formulario form = new Formulario();
        form.setVisible(true);
    }//GEN-LAST:event_botonNuevaVentanaActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        
        CargarTabla(txtBuscar.getText(),comboClientes.getSelectedIndex());
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void EmergenteEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergenteEliminarActionPerformed
        int fila = TablaCliente.getSelectedRow(), resp;
        if(fila >0 ){
            resp = JOptionPane.showConfirmDialog(null,"Esta seguro de eliminar el cliente: "+TablaCliente.getValueAt(fila,1)
            ,"Advertencia",JOptionPane.WARNING_MESSAGE);
            if(resp == 0){
                conexion.conexion.EjecutarInstruccion("delete from cliente where id = "+TablaCliente.getValueAt(fila,0));
                //JOptionPane.showMessageDialog(null,"Cliente eliminado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                CargarTabla("",comboClientes.getSelectedIndex());
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Seleccione una registro","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EmergenteEliminarActionPerformed

    private void botonCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCommitActionPerformed
        conexion.conexion.EjecutarInstruccion("commit");
        botonCommit.setEnabled(false);
        botonRollBack.setEnabled(false);
        botonIniciarTran.setEnabled(true);
        CargarTabla("",comboClientes.getSelectedIndex());
    }//GEN-LAST:event_botonCommitActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
      DialogNuevo.setVisible(true);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if(txtDireccion.getText().length()>0&&txtNit.getText().length()>0&&txtDireccion.getText().length()>0){
            String consula = "insert into cliente(Nombre,Nit,Direccion,Saldo) values('"+
                    txtNombre.getText()+"','"+txtNit.getText()+"','"+txtDireccion.getText()+"',"+0+")"
                    ;
            conexion.conexion.EjecutarInstruccion(consula);
            DialogNuevo.dispose();
            txtDireccion.setText("");
            txtNit.setText("");
            txtNombre.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null,"Llene todos los campos","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        DialogNuevo.dispose();
        txtDireccion.setText("");
        txtNit.setText("");
        txtNombre.setText("");
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JDialog DialogNuevo;
    private javax.swing.JMenuItem EmergenteEliminar;
    private javax.swing.JPopupMenu MenuEmergente;
    private javax.swing.JMenu ModificarAislamiento;
    private javax.swing.JMenuItem ReadCommitted;
    private javax.swing.JMenuItem ReadUncommitted;
    private javax.swing.JMenuItem RepeatableRead;
    private javax.swing.JMenuItem Serializable;
    private rojerusan.RSTableMetro TablaCliente;
    private javax.swing.JMenuItem VerAsilamiento;
    private rojeru_san.RSButton botonAceptar;
    private rojeru_san.RSButton botonBuscar;
    private rojeru_san.RSButton botonCancelar;
    private rojeru_san.RSButtonRiple botonCommit;
    private rojeru_san.RSButtonRiple botonIniciarTran;
    private rojeru_san.RSButton botonNuevaVentana;
    private rojeru_san.RSButton botonNuevo;
    private rojeru_san.RSButtonRiple botonRecargarBD;
    private rojeru_san.RSButtonRiple botonRollBack;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTabla;
    private rojeru_san.RSPanelsSlider rsPanel;
    private rojeru_san.RSMTextFull txtBuscar;
    private rojeru_san.RSMTextFull txtDireccion;
    private rojeru_san.RSMTextFull txtNit;
    private rojeru_san.RSMTextFull txtNombre;
    // End of variables declaration//GEN-END:variables
}
