/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transacciones_1_0;
import Clases.VariableGlobal;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Formulario extends javax.swing.JFrame {

    private VariableGlobal conexion;
    public Formulario() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Transacciones");
        conexion = new VariableGlobal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        BarraDeMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ModificarAislamiento = new javax.swing.JMenu();
        ReadUncommitted = new javax.swing.JMenuItem();
        ReadCommitted = new javax.swing.JMenuItem();
        RepeatableRead = new javax.swing.JMenuItem();
        Serializable = new javax.swing.JMenuItem();
        VerAsilamiento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jMenu1.setText("Aislamiento");

        ModificarAislamiento.setText("Modificar aislamiento");

        ReadUncommitted.setText("Leer no comprometido");
        ReadUncommitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadUncommittedActionPerformed(evt);
            }
        });
        ModificarAislamiento.add(ReadUncommitted);

        ReadCommitted.setText("Leer comprometido");
        ReadCommitted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadCommittedActionPerformed(evt);
            }
        });
        ModificarAislamiento.add(ReadCommitted);

        RepeatableRead.setText("Leer repetido");
        RepeatableRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatableReadActionPerformed(evt);
            }
        });
        ModificarAislamiento.add(RepeatableRead);

        Serializable.setText("Serializable");
        Serializable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerializableActionPerformed(evt);
            }
        });
        ModificarAislamiento.add(Serializable);

        jMenu1.add(ModificarAislamiento);

        VerAsilamiento.setText("Ver aislamiento");
        VerAsilamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerAsilamientoActionPerformed(evt);
            }
        });
        jMenu1.add(VerAsilamiento);

        BarraDeMenu.add(jMenu1);

        jMenu2.setText("Operaciones");
        BarraDeMenu.add(jMenu2);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   //Cambia el nivel de aislamiento
    private void cambioAislamiento(String aisla){
        int resp = JOptionPane.showConfirmDialog(null,"¿Esta seguro de cambiar "+"\nel nivel de aislamiento a "+aisla+"?","¡Alerta"
        ,JOptionPane.YES_NO_OPTION);
        if(resp == 0){
           conexion.conexion.EjecutarInstruccion("SET GLOBAL TRANSACTION ISOLATION LEVEL "+aisla);//Ejecutamos la sentencia para cambiar el aislamiento
           JOptionPane.showMessageDialog(null,"El aislamiento fue cambiado");
           conexion.conexion.CerrarConexion();//Cerramos la conexion 
           conexion = new VariableGlobal();//Instanciamos un nuevamente la variable conexion. Para poder ver los cambios
        }
    }
    //Ver el aislamiento de la base
    private void VerAsilamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerAsilamientoActionPerformed
        String nivelAislamiento = "";
        conexion.conexion.EjecutarConsulta("show variables like 'tx_isolation'");//Realizamos la consulta 
        ResultSet rs = conexion.conexion.getResultSet();//Obtenemos el ResultSet, que tiene los registros de la consulta
        try {
            while(rs.next()){//Recorremos todos los registros de la consulta. 
                nivelAislamiento = rs.getString("Value");//Retornamos el dato que este en la columna Values. Que es donde esta el nivel de aislamiento
            }
        } catch (Exception e) {
        }
        JOptionPane.showMessageDialog(null,"EL nivle de aislamiento es: "+nivelAislamiento,"",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_VerAsilamientoActionPerformed

    private void SerializableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerializableActionPerformed
        cambioAislamiento("SERIALIZABLE");
    }//GEN-LAST:event_SerializableActionPerformed

    private void RepeatableReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatableReadActionPerformed
        cambioAislamiento("REPEATABLE READ");
    }//GEN-LAST:event_RepeatableReadActionPerformed

    private void ReadCommittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadCommittedActionPerformed
        cambioAislamiento("READ COMMITTED");
    }//GEN-LAST:event_ReadCommittedActionPerformed

    private void ReadUncommittedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadUncommittedActionPerformed
        cambioAislamiento("READ UNCOMMITTED");
    }//GEN-LAST:event_ReadUncommittedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JMenu ModificarAislamiento;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JMenuItem ReadCommitted;
    private javax.swing.JMenuItem ReadUncommitted;
    private javax.swing.JMenuItem RepeatableRead;
    private javax.swing.JMenuItem Serializable;
    private javax.swing.JMenuItem VerAsilamiento;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
